/**
 * Hygen Template Helpers
 * Utility functions for code generation templates
 */

module.exports = {
  /**
   * Convert string to PascalCase
   * Example: 'user-profile' -> 'UserProfile'
   */
  toPascalCase: (str) => {
    return str
      .split(/[-_\s]+/)
      .map(word => word.charAt(0).toUpperCase() + word.slice(1).toLowerCase())
      .join('');
  },

  /**
   * Convert string to camelCase
   * Example: 'user-profile' -> 'userProfile'
   */
  toCamelCase: (str) => {
    const pascal = module.exports.toPascalCase(str);
    return pascal.charAt(0).toLowerCase() + pascal.slice(1);
  },

  /**
   * Convert string to kebab-case
   * Example: 'UserProfile' -> 'user-profile'
   */
  toKebabCase: (str) => {
    return str
      .replace(/([a-z])([A-Z])/g, '$1-$2')
      .replace(/[\s_]+/g, '-')
      .toLowerCase();
  },

  /**
   * Convert string to snake_case
   * Example: 'UserProfile' -> 'user_profile'
   */
  toSnakeCase: (str) => {
    return str
      .replace(/([a-z])([A-Z])/g, '$1_$2')
      .replace(/[\s-]+/g, '_')
      .toLowerCase();
  },

  /**
   * Convert string to UPPER_SNAKE_CASE
   * Example: 'order-service' -> 'ORDER_SERVICE'
   */
  toUpperSnakeCase: (str) => {
    return str
      .replace(/([a-z])([A-Z])/g, '$1_$2')
      .replace(/[\s-]+/g, '_')
      .toUpperCase();
  },

  /**
   * Pluralize a word (simple implementation)
   * Example: 'user' -> 'users'
   */
  pluralize: (str) => {
    if (str.endsWith('s') || str.endsWith('x') || str.endsWith('ch') || str.endsWith('sh')) {
      return str + 'es';
    }
    if (str.endsWith('y') && !/[aeiou]y$/.test(str)) {
      return str.slice(0, -1) + 'ies';
    }
    return str + 's';
  },

  /**
   * Get current timestamp in format YYMMDD-HHMM
   */
  timestamp: () => {
    const now = new Date();
    const yy = String(now.getFullYear()).slice(-2);
    const mm = String(now.getMonth() + 1).padStart(2, '0');
    const dd = String(now.getDate()).padStart(2, '0');
    const hh = String(now.getHours()).padStart(2, '0');
    const min = String(now.getMinutes()).padStart(2, '0');
    return `${yy}${mm}${dd}-${hh}${min}`;
  },

  /**
   * Get default TCP port based on service name
   */
  getDefaultPort: (serviceName) => {
    const basePort = 3000;
    const serviceMap = {
      'applicant': 3002,
      'customer': 3002,
      'admin': 3003,
      'auth': 3004,
      'gateway': 3000,
      'address': 3005,
      'order': 3006,
      'product': 3007,
      'notification': 3008,
    };

    // Check if service name matches known services
    const lowerName = serviceName.toLowerCase();
    for (const [key, port] of Object.entries(serviceMap)) {
      if (lowerName.includes(key)) {
        return port;
      }
    }

    // Generate port based on service name hash
    let hash = 0;
    for (let i = 0; i < serviceName.length; i++) {
      hash = ((hash << 5) - hash) + serviceName.charCodeAt(i);
      hash = hash & hash;
    }
    return basePort + 10 + Math.abs(hash % 85); // Ports 3010-3095
  },

  /**
   * Get default health port (TCP port + 10)
   */
  getDefaultHealthPort: (tcpPort) => {
    return parseInt(tcpPort, 10) + 10;
  },

  /**
   * Validate service name (lowercase, alphanumeric, hyphens only)
   */
  isValidServiceName: (name) => {
    return /^[a-z][a-z0-9-]*$/.test(name);
  },

  /**
   * Validate entity name (lowercase, alphanumeric, hyphens only, singular)
   */
  isValidEntityName: (name) => {
    if (!name || typeof name !== 'string') return false;
    // Must start with lowercase letter, contain only lowercase letters, numbers, hyphens
    // Should not end with 's' (singular form expected)
    return /^[a-z][a-z0-9-]*[^s]$/.test(name) || /^[a-z]$/.test(name);
  },

  /**
   * Generate copyright header
   */
  copyrightHeader: () => {
    const year = new Date().getFullYear();
    return `/**
 * Copyright (c) ${year}
 * Generated by Hygen - Vietnam New Address Core
 */`;
  },
};
