/**
 * Hygen Template Helpers
 * Utility functions for code generation templates
 */

module.exports = {
  /**
   * Convert string to PascalCase
   * Example: 'user-profile' -> 'UserProfile'
   */
  toPascalCase: (str) => {
    return str
      .split(/[-_\s]+/)
      .map(word => word.charAt(0).toUpperCase() + word.slice(1).toLowerCase())
      .join('');
  },

  /**
   * Convert string to camelCase
   * Example: 'user-profile' -> 'userProfile'
   */
  toCamelCase: (str) => {
    const pascal = module.exports.toPascalCase(str);
    return pascal.charAt(0).toLowerCase() + pascal.slice(1);
  },

  /**
   * Convert string to kebab-case
   * Example: 'UserProfile' -> 'user-profile'
   */
  toKebabCase: (str) => {
    return str
      .replace(/([a-z])([A-Z])/g, '$1-$2')
      .replace(/[\s_]+/g, '-')
      .toLowerCase();
  },

  /**
   * Convert string to snake_case
   * Example: 'UserProfile' -> 'user_profile'
   */
  toSnakeCase: (str) => {
    return str
      .replace(/([a-z])([A-Z])/g, '$1_$2')
      .replace(/[\s-]+/g, '_')
      .toLowerCase();
  },

  /**
   * Pluralize a word (simple implementation)
   * Example: 'user' -> 'users'
   */
  pluralize: (str) => {
    if (str.endsWith('s') || str.endsWith('x') || str.endsWith('ch') || str.endsWith('sh')) {
      return str + 'es';
    }
    if (str.endsWith('y') && !/[aeiou]y$/.test(str)) {
      return str.slice(0, -1) + 'ies';
    }
    return str + 's';
  },

  /**
   * Get current timestamp in format YYMMDD-HHMM
   */
  timestamp: () => {
    const now = new Date();
    const yy = String(now.getFullYear()).slice(-2);
    const mm = String(now.getMonth() + 1).padStart(2, '0');
    const dd = String(now.getDate()).padStart(2, '0');
    const hh = String(now.getHours()).padStart(2, '0');
    const min = String(now.getMinutes()).padStart(2, '0');
    return `${yy}${mm}${dd}-${hh}${min}`;
  },

  /**
   * Get default TCP port based on service name
   */
  getDefaultPort: (serviceName) => {
    const basePort = 3000;
    const serviceMap = {
      'customer': 3002,
      'admin': 3003,
      'auth': 3004,
      'gateway': 3000,
    };

    // Check if service name matches known services
    const lowerName = serviceName.toLowerCase();
    for (const [key, port] of Object.entries(serviceMap)) {
      if (lowerName.includes(key)) {
        return port;
      }
    }

    // Generate port based on service name hash
    let hash = 0;
    for (let i = 0; i < serviceName.length; i++) {
      hash = ((hash << 5) - hash) + serviceName.charCodeAt(i);
      hash = hash & hash;
    }
    return basePort + 5 + Math.abs(hash % 90); // Ports 3005-3095
  },

  /**
   * Validate service name (lowercase, alphanumeric, hyphens only)
   */
  isValidServiceName: (name) => {
    return /^[a-z][a-z0-9-]*$/.test(name);
  },

  /**
   * Generate copyright header
   */
  copyrightHeader: () => {
    const year = new Date().getFullYear();
    return `/**
 * Copyright (c) ${year}
 * Generated by Hygen - Vietnam Address Core
 */`;
  },
};
