/**
 * ISO 3166-1 Country Data
 * Full list of 249 countries with alpha-2, alpha-3 codes and English names
 * Source: https://www.iso.org/obp/ui/#search/code/
 */

export interface Country {
  code: string; // ISO 3166-1 alpha-2
  name: string; // English name
  alpha3: string; // ISO 3166-1 alpha-3
}

export const COUNTRIES: Country[] = [
  { code: 'AF', name: 'Afghanistan', alpha3: 'AFG' },
  { code: 'AL', name: 'Albania', alpha3: 'ALB' },
  { code: 'DZ', name: 'Algeria', alpha3: 'DZA' },
  { code: 'AS', name: 'American Samoa', alpha3: 'ASM' },
  { code: 'AD', name: 'Andorra', alpha3: 'AND' },
  { code: 'AO', name: 'Angola', alpha3: 'AGO' },
  { code: 'AI', name: 'Anguilla', alpha3: 'AIA' },
  { code: 'AQ', name: 'Antarctica', alpha3: 'ATA' },
  { code: 'AG', name: 'Antigua and Barbuda', alpha3: 'ATG' },
  { code: 'AR', name: 'Argentina', alpha3: 'ARG' },
  { code: 'AM', name: 'Armenia', alpha3: 'ARM' },
  { code: 'AW', name: 'Aruba', alpha3: 'ABW' },
  { code: 'AU', name: 'Australia', alpha3: 'AUS' },
  { code: 'AT', name: 'Austria', alpha3: 'AUT' },
  { code: 'AZ', name: 'Azerbaijan', alpha3: 'AZE' },
  { code: 'BS', name: 'Bahamas', alpha3: 'BHS' },
  { code: 'BH', name: 'Bahrain', alpha3: 'BHR' },
  { code: 'BD', name: 'Bangladesh', alpha3: 'BGD' },
  { code: 'BB', name: 'Barbados', alpha3: 'BRB' },
  { code: 'BY', name: 'Belarus', alpha3: 'BLR' },
  { code: 'BE', name: 'Belgium', alpha3: 'BEL' },
  { code: 'BZ', name: 'Belize', alpha3: 'BLZ' },
  { code: 'BJ', name: 'Benin', alpha3: 'BEN' },
  { code: 'BM', name: 'Bermuda', alpha3: 'BMU' },
  { code: 'BT', name: 'Bhutan', alpha3: 'BTN' },
  { code: 'BO', name: 'Bolivia', alpha3: 'BOL' },
  { code: 'BQ', name: 'Bonaire, Sint Eustatius and Saba', alpha3: 'BES' },
  { code: 'BA', name: 'Bosnia and Herzegovina', alpha3: 'BIH' },
  { code: 'BW', name: 'Botswana', alpha3: 'BWA' },
  { code: 'BV', name: 'Bouvet Island', alpha3: 'BVT' },
  { code: 'BR', name: 'Brazil', alpha3: 'BRA' },
  { code: 'IO', name: 'British Indian Ocean Territory', alpha3: 'IOT' },
  { code: 'BN', name: 'Brunei Darussalam', alpha3: 'BRN' },
  { code: 'BG', name: 'Bulgaria', alpha3: 'BGR' },
  { code: 'BF', name: 'Burkina Faso', alpha3: 'BFA' },
  { code: 'BI', name: 'Burundi', alpha3: 'BDI' },
  { code: 'CV', name: 'Cabo Verde', alpha3: 'CPV' },
  { code: 'KH', name: 'Cambodia', alpha3: 'KHM' },
  { code: 'CM', name: 'Cameroon', alpha3: 'CMR' },
  { code: 'CA', name: 'Canada', alpha3: 'CAN' },
  { code: 'KY', name: 'Cayman Islands', alpha3: 'CYM' },
  { code: 'CF', name: 'Central African Republic', alpha3: 'CAF' },
  { code: 'TD', name: 'Chad', alpha3: 'TCD' },
  { code: 'CL', name: 'Chile', alpha3: 'CHL' },
  { code: 'CN', name: 'China', alpha3: 'CHN' },
  { code: 'CX', name: 'Christmas Island', alpha3: 'CXR' },
  { code: 'CC', name: 'Cocos (Keeling) Islands', alpha3: 'CCK' },
  { code: 'CO', name: 'Colombia', alpha3: 'COL' },
  { code: 'KM', name: 'Comoros', alpha3: 'COM' },
  { code: 'CD', name: 'Congo (Democratic Republic)', alpha3: 'COD' },
  { code: 'CG', name: 'Congo', alpha3: 'COG' },
  { code: 'CK', name: 'Cook Islands', alpha3: 'COK' },
  { code: 'CR', name: 'Costa Rica', alpha3: 'CRI' },
  { code: 'HR', name: 'Croatia', alpha3: 'HRV' },
  { code: 'CU', name: 'Cuba', alpha3: 'CUB' },
  { code: 'CW', name: 'Curaçao', alpha3: 'CUW' },
  { code: 'CY', name: 'Cyprus', alpha3: 'CYP' },
  { code: 'CZ', name: 'Czechia', alpha3: 'CZE' },
  { code: 'CI', name: "Côte d'Ivoire", alpha3: 'CIV' },
  { code: 'DK', name: 'Denmark', alpha3: 'DNK' },
  { code: 'DJ', name: 'Djibouti', alpha3: 'DJI' },
  { code: 'DM', name: 'Dominica', alpha3: 'DMA' },
  { code: 'DO', name: 'Dominican Republic', alpha3: 'DOM' },
  { code: 'EC', name: 'Ecuador', alpha3: 'ECU' },
  { code: 'EG', name: 'Egypt', alpha3: 'EGY' },
  { code: 'SV', name: 'El Salvador', alpha3: 'SLV' },
  { code: 'GQ', name: 'Equatorial Guinea', alpha3: 'GNQ' },
  { code: 'ER', name: 'Eritrea', alpha3: 'ERI' },
  { code: 'EE', name: 'Estonia', alpha3: 'EST' },
  { code: 'SZ', name: 'Eswatini', alpha3: 'SWZ' },
  { code: 'ET', name: 'Ethiopia', alpha3: 'ETH' },
  { code: 'FK', name: 'Falkland Islands', alpha3: 'FLK' },
  { code: 'FO', name: 'Faroe Islands', alpha3: 'FRO' },
  { code: 'FJ', name: 'Fiji', alpha3: 'FJI' },
  { code: 'FI', name: 'Finland', alpha3: 'FIN' },
  { code: 'FR', name: 'France', alpha3: 'FRA' },
  { code: 'GF', name: 'French Guiana', alpha3: 'GUF' },
  { code: 'PF', name: 'French Polynesia', alpha3: 'PYF' },
  { code: 'TF', name: 'French Southern Territories', alpha3: 'ATF' },
  { code: 'GA', name: 'Gabon', alpha3: 'GAB' },
  { code: 'GM', name: 'Gambia', alpha3: 'GMB' },
  { code: 'GE', name: 'Georgia', alpha3: 'GEO' },
  { code: 'DE', name: 'Germany', alpha3: 'DEU' },
  { code: 'GH', name: 'Ghana', alpha3: 'GHA' },
  { code: 'GI', name: 'Gibraltar', alpha3: 'GIB' },
  { code: 'GR', name: 'Greece', alpha3: 'GRC' },
  { code: 'GL', name: 'Greenland', alpha3: 'GRL' },
  { code: 'GD', name: 'Grenada', alpha3: 'GRD' },
  { code: 'GP', name: 'Guadeloupe', alpha3: 'GLP' },
  { code: 'GU', name: 'Guam', alpha3: 'GUM' },
  { code: 'GT', name: 'Guatemala', alpha3: 'GTM' },
  { code: 'GG', name: 'Guernsey', alpha3: 'GGY' },
  { code: 'GN', name: 'Guinea', alpha3: 'GIN' },
  { code: 'GW', name: 'Guinea-Bissau', alpha3: 'GNB' },
  { code: 'GY', name: 'Guyana', alpha3: 'GUY' },
  { code: 'HT', name: 'Haiti', alpha3: 'HTI' },
  { code: 'HM', name: 'Heard Island and McDonald Islands', alpha3: 'HMD' },
  { code: 'VA', name: 'Holy See', alpha3: 'VAT' },
  { code: 'HN', name: 'Honduras', alpha3: 'HND' },
  { code: 'HK', name: 'Hong Kong', alpha3: 'HKG' },
  { code: 'HU', name: 'Hungary', alpha3: 'HUN' },
  { code: 'IS', name: 'Iceland', alpha3: 'ISL' },
  { code: 'IN', name: 'India', alpha3: 'IND' },
  { code: 'ID', name: 'Indonesia', alpha3: 'IDN' },
  { code: 'IR', name: 'Iran', alpha3: 'IRN' },
  { code: 'IQ', name: 'Iraq', alpha3: 'IRQ' },
  { code: 'IE', name: 'Ireland', alpha3: 'IRL' },
  { code: 'IM', name: 'Isle of Man', alpha3: 'IMN' },
  { code: 'IL', name: 'Israel', alpha3: 'ISR' },
  { code: 'IT', name: 'Italy', alpha3: 'ITA' },
  { code: 'JM', name: 'Jamaica', alpha3: 'JAM' },
  { code: 'JP', name: 'Japan', alpha3: 'JPN' },
  { code: 'JE', name: 'Jersey', alpha3: 'JEY' },
  { code: 'JO', name: 'Jordan', alpha3: 'JOR' },
  { code: 'KZ', name: 'Kazakhstan', alpha3: 'KAZ' },
  { code: 'KE', name: 'Kenya', alpha3: 'KEN' },
  { code: 'KI', name: 'Kiribati', alpha3: 'KIR' },
  { code: 'KP', name: 'Korea (Democratic)', alpha3: 'PRK' },
  { code: 'KR', name: 'Korea (Republic)', alpha3: 'KOR' },
  { code: 'KW', name: 'Kuwait', alpha3: 'KWT' },
  { code: 'KG', name: 'Kyrgyzstan', alpha3: 'KGZ' },
  { code: 'LA', name: 'Lao', alpha3: 'LAO' },
  { code: 'LV', name: 'Latvia', alpha3: 'LVA' },
  { code: 'LB', name: 'Lebanon', alpha3: 'LBN' },
  { code: 'LS', name: 'Lesotho', alpha3: 'LSO' },
  { code: 'LR', name: 'Liberia', alpha3: 'LBR' },
  { code: 'LY', name: 'Libya', alpha3: 'LBY' },
  { code: 'LI', name: 'Liechtenstein', alpha3: 'LIE' },
  { code: 'LT', name: 'Lithuania', alpha3: 'LTU' },
  { code: 'LU', name: 'Luxembourg', alpha3: 'LUX' },
  { code: 'MO', name: 'Macao', alpha3: 'MAC' },
  { code: 'MG', name: 'Madagascar', alpha3: 'MDG' },
  { code: 'MW', name: 'Malawi', alpha3: 'MWI' },
  { code: 'MY', name: 'Malaysia', alpha3: 'MYS' },
  { code: 'MV', name: 'Maldives', alpha3: 'MDV' },
  { code: 'ML', name: 'Mali', alpha3: 'MLI' },
  { code: 'MT', name: 'Malta', alpha3: 'MLT' },
  { code: 'MH', name: 'Marshall Islands', alpha3: 'MHL' },
  { code: 'MQ', name: 'Martinique', alpha3: 'MTQ' },
  { code: 'MR', name: 'Mauritania', alpha3: 'MRT' },
  { code: 'MU', name: 'Mauritius', alpha3: 'MUS' },
  { code: 'YT', name: 'Mayotte', alpha3: 'MYT' },
  { code: 'MX', name: 'Mexico', alpha3: 'MEX' },
  { code: 'FM', name: 'Micronesia', alpha3: 'FSM' },
  { code: 'MD', name: 'Moldova', alpha3: 'MDA' },
  { code: 'MC', name: 'Monaco', alpha3: 'MCO' },
  { code: 'MN', name: 'Mongolia', alpha3: 'MNG' },
  { code: 'ME', name: 'Montenegro', alpha3: 'MNE' },
  { code: 'MS', name: 'Montserrat', alpha3: 'MSR' },
  { code: 'MA', name: 'Morocco', alpha3: 'MAR' },
  { code: 'MZ', name: 'Mozambique', alpha3: 'MOZ' },
  { code: 'MM', name: 'Myanmar', alpha3: 'MMR' },
  { code: 'NA', name: 'Namibia', alpha3: 'NAM' },
  { code: 'NR', name: 'Nauru', alpha3: 'NRU' },
  { code: 'NP', name: 'Nepal', alpha3: 'NPL' },
  { code: 'NL', name: 'Netherlands', alpha3: 'NLD' },
  { code: 'NC', name: 'New Caledonia', alpha3: 'NCL' },
  { code: 'NZ', name: 'New Zealand', alpha3: 'NZL' },
  { code: 'NI', name: 'Nicaragua', alpha3: 'NIC' },
  { code: 'NE', name: 'Niger', alpha3: 'NER' },
  { code: 'NG', name: 'Nigeria', alpha3: 'NGA' },
  { code: 'NU', name: 'Niue', alpha3: 'NIU' },
  { code: 'NF', name: 'Norfolk Island', alpha3: 'NFK' },
  { code: 'MK', name: 'North Macedonia', alpha3: 'MKD' },
  { code: 'MP', name: 'Northern Mariana Islands', alpha3: 'MNP' },
  { code: 'NO', name: 'Norway', alpha3: 'NOR' },
  { code: 'OM', name: 'Oman', alpha3: 'OMN' },
  { code: 'PK', name: 'Pakistan', alpha3: 'PAK' },
  { code: 'PW', name: 'Palau', alpha3: 'PLW' },
  { code: 'PS', name: 'Palestine', alpha3: 'PSE' },
  { code: 'PA', name: 'Panama', alpha3: 'PAN' },
  { code: 'PG', name: 'Papua New Guinea', alpha3: 'PNG' },
  { code: 'PY', name: 'Paraguay', alpha3: 'PRY' },
  { code: 'PE', name: 'Peru', alpha3: 'PER' },
  { code: 'PH', name: 'Philippines', alpha3: 'PHL' },
  { code: 'PN', name: 'Pitcairn', alpha3: 'PCN' },
  { code: 'PL', name: 'Poland', alpha3: 'POL' },
  { code: 'PT', name: 'Portugal', alpha3: 'PRT' },
  { code: 'PR', name: 'Puerto Rico', alpha3: 'PRI' },
  { code: 'QA', name: 'Qatar', alpha3: 'QAT' },
  { code: 'RO', name: 'Romania', alpha3: 'ROU' },
  { code: 'RU', name: 'Russian Federation', alpha3: 'RUS' },
  { code: 'RW', name: 'Rwanda', alpha3: 'RWA' },
  { code: 'RE', name: 'Réunion', alpha3: 'REU' },
  { code: 'BL', name: 'Saint Barthélemy', alpha3: 'BLM' },
  { code: 'SH', name: 'Saint Helena, Ascension and Tristan da Cunha', alpha3: 'SHN' },
  { code: 'KN', name: 'Saint Kitts and Nevis', alpha3: 'KNA' },
  { code: 'LC', name: 'Saint Lucia', alpha3: 'LCA' },
  { code: 'MF', name: 'Saint Martin (French)', alpha3: 'MAF' },
  { code: 'PM', name: 'Saint Pierre and Miquelon', alpha3: 'SPM' },
  { code: 'VC', name: 'Saint Vincent and the Grenadines', alpha3: 'VCT' },
  { code: 'WS', name: 'Samoa', alpha3: 'WSM' },
  { code: 'SM', name: 'San Marino', alpha3: 'SMR' },
  { code: 'ST', name: 'Sao Tome and Principe', alpha3: 'STP' },
  { code: 'SA', name: 'Saudi Arabia', alpha3: 'SAU' },
  { code: 'SN', name: 'Senegal', alpha3: 'SEN' },
  { code: 'RS', name: 'Serbia', alpha3: 'SRB' },
  { code: 'SC', name: 'Seychelles', alpha3: 'SYC' },
  { code: 'SL', name: 'Sierra Leone', alpha3: 'SLE' },
  { code: 'SG', name: 'Singapore', alpha3: 'SGP' },
  { code: 'SX', name: 'Sint Maarten (Dutch)', alpha3: 'SXM' },
  { code: 'SK', name: 'Slovakia', alpha3: 'SVK' },
  { code: 'SI', name: 'Slovenia', alpha3: 'SVN' },
  { code: 'SB', name: 'Solomon Islands', alpha3: 'SLB' },
  { code: 'SO', name: 'Somalia', alpha3: 'SOM' },
  { code: 'ZA', name: 'South Africa', alpha3: 'ZAF' },
  { code: 'GS', name: 'South Georgia and the South Sandwich Islands', alpha3: 'SGS' },
  { code: 'SS', name: 'South Sudan', alpha3: 'SSD' },
  { code: 'ES', name: 'Spain', alpha3: 'ESP' },
  { code: 'LK', name: 'Sri Lanka', alpha3: 'LKA' },
  { code: 'SD', name: 'Sudan', alpha3: 'SDN' },
  { code: 'SR', name: 'Suriname', alpha3: 'SUR' },
  { code: 'SJ', name: 'Svalbard and Jan Mayen', alpha3: 'SJM' },
  { code: 'SE', name: 'Sweden', alpha3: 'SWE' },
  { code: 'CH', name: 'Switzerland', alpha3: 'CHE' },
  { code: 'SY', name: 'Syrian Arab Republic', alpha3: 'SYR' },
  { code: 'TW', name: 'Taiwan', alpha3: 'TWN' },
  { code: 'TJ', name: 'Tajikistan', alpha3: 'TJK' },
  { code: 'TZ', name: 'Tanzania', alpha3: 'TZA' },
  { code: 'TH', name: 'Thailand', alpha3: 'THA' },
  { code: 'TL', name: 'Timor-Leste', alpha3: 'TLS' },
  { code: 'TG', name: 'Togo', alpha3: 'TGO' },
  { code: 'TK', name: 'Tokelau', alpha3: 'TKL' },
  { code: 'TO', name: 'Tonga', alpha3: 'TON' },
  { code: 'TT', name: 'Trinidad and Tobago', alpha3: 'TTO' },
  { code: 'TN', name: 'Tunisia', alpha3: 'TUN' },
  { code: 'TM', name: 'Turkmenistan', alpha3: 'TKM' },
  { code: 'TC', name: 'Turks and Caicos Islands', alpha3: 'TCA' },
  { code: 'TV', name: 'Tuvalu', alpha3: 'TUV' },
  { code: 'TR', name: 'Türkiye', alpha3: 'TUR' },
  { code: 'UG', name: 'Uganda', alpha3: 'UGA' },
  { code: 'UA', name: 'Ukraine', alpha3: 'UKR' },
  { code: 'AE', name: 'United Arab Emirates', alpha3: 'ARE' },
  { code: 'GB', name: 'United Kingdom', alpha3: 'GBR' },
  { code: 'UM', name: 'United States Minor Outlying Islands', alpha3: 'UMI' },
  { code: 'US', name: 'United States', alpha3: 'USA' },
  { code: 'UY', name: 'Uruguay', alpha3: 'URY' },
  { code: 'UZ', name: 'Uzbekistan', alpha3: 'UZB' },
  { code: 'VU', name: 'Vanuatu', alpha3: 'VUT' },
  { code: 'VE', name: 'Venezuela', alpha3: 'VEN' },
  { code: 'VN', name: 'Viet Nam', alpha3: 'VNM' },
  { code: 'VG', name: 'Virgin Islands (British)', alpha3: 'VGB' },
  { code: 'VI', name: 'Virgin Islands (U.S.)', alpha3: 'VIR' },
  { code: 'WF', name: 'Wallis and Futuna', alpha3: 'WLF' },
  { code: 'EH', name: 'Western Sahara', alpha3: 'ESH' },
  { code: 'YE', name: 'Yemen', alpha3: 'YEM' },
  { code: 'ZM', name: 'Zambia', alpha3: 'ZMB' },
  { code: 'ZW', name: 'Zimbabwe', alpha3: 'ZWE' },
  { code: 'AX', name: 'Åland Islands', alpha3: 'ALA' },
];

// Extract just the alpha-2 codes for validation
export const COUNTRY_CODES = COUNTRIES.map((c) => c.code);

/**
 * Validate if a string is a valid ISO 3166-1 alpha-2 country code
 */
export const isValidCountryCode = (code: string): boolean => {
  return COUNTRY_CODES.includes(code.toUpperCase());
};

/**
 * Get country by alpha-2 code
 */
export const getCountryByCode = (code: string): Country | undefined => {
  return COUNTRIES.find((c) => c.code === code.toUpperCase());
};

/**
 * Get country by alpha-3 code
 */
export const getCountryByAlpha3 = (alpha3: string): Country | undefined => {
  return COUNTRIES.find((c) => c.alpha3 === alpha3.toUpperCase());
};
